### ISSUE TITLE
UY Holidays are incorrect. It's not considering workable holidays.

### ISSUE THREAD

**Issue by sferreiro** [rogerpadilla/adp#14]
For example. Oct-12, it is in fact an official holiday but is a workable one usually the public sector doesn't work it (and banks) but in the private sector (us) that means we work it.
If people doesn't pay attention to this and change the day to Regular manually they may end up filling incorrect days.

**Comment by rogerpadilla** [comment]
@sferreiro the library used to obtain the holidays of each country was recently upgraded to the latest version, this was released in the version 0.7.3 of the adp-next plugin.

This issue might be fixed in such latest version of adp-next... would you check if you are using that version and if that is still reproducible there? (can be checked by opening this URL in Chrome [chrome://extensions/](chrome://extensions/)

**Comment by rogerpadilla** [comment]
Closing this due to inactivity. So assuming it was solved in the latest release.

**Comment by sferreiro** [comment]
Still not working. 
Here is another example. November 2nd is not a holiday. I'm using version 0.7.4
 
![image](https://user-images.githubusercontent.com/11488517/47850344-a8762680-ddb3-11e8-8903-41c47c1cc88e.png)
